name: Deploy NGINX to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: arc-runner-set

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Set KUBECONFIG environment variable
      run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

    - name: Apply NGINX Deployment
      run: kubectl apply -f nginx-deployment.yaml

    - name: Verify NGINX Deployment
      run: kubectl rollout status deployment/nginx-deployment
